# run: conda env create --file environment.yml
name: image_processing
dependencies:
- python>=3.7
- conda
- numpy
- pandas
- seaborn
- jupyter
- xmltodict
- dask
- pip
- pip:
  # works for regular pip packages
  - czifle
  - apeer-dev-kit
  - apeer-ometiff-library
  - napari
  - aicsimageio
  - czmodel
  - zarr
  - javabridge
  - python-bioformats
#  # and for wheels
#  - https://www.lfd.uci.edu/~gohlke/pythonlibs/#javabridge
